openapi: 3.0.3
info:
  title: API Biblioteca UPEL - Reservas de Libros
  version: 1.0.0
  description: Documentaci贸n de la API de gesti贸n de reservas (holds) de la biblioteca UPEL
servers:
  - url: http://localhost:3000
paths:
  /holds:
    get:
      summary: Obtener todas las reservas
      tags: [Holds]
      responses:
        200:
          description: Lista de reservas
    post:
      summary: Crear una nueva reserva
      tags: [Holds]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HoldInput'
      responses:
        201:
          description: Reserva creada
        400:
          description: Error de validaci贸n
  /holds/{id}:
    get:
      summary: Obtener una reserva por ID
      tags: [Holds]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Reserva encontrada
        404:
          description: Reserva no encontrada
    put:
      summary: Actualizar una reserva
      tags: [Holds]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HoldUpdate'
      responses:
        200:
          description: Reserva actualizada
        400:
          description: Error de validaci贸n
        404:
          description: Reserva no encontrada
    delete:
      summary: Eliminar una reserva
      tags: [Holds]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Reserva eliminada
        404:
          description: Reserva no encontrada
components:
  schemas:
    HoldInput:
      type: object
      required:
        - book_id
        - user_id
        - status
      properties:
        book_id:
          type: integer
        user_id:
          type: integer
        expiry_date:
          type: string
          format: date
        status:
          type: string
          enum: [pending, fulfilled, cancelled]
    HoldUpdate:
      type: object
      properties:
        expiry_date:
          type: string
          format: date
        status:
          type: string
          enum: [pending, fulfilled, cancelled]
